---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: the-listener
spec:
  triggers:
  - binding:
      name: theTriggerBinding
    template:
      name: theTemplateTrigger
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: theTriggerBinding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: theTemplateTrigger
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
  - name: xx1
    taskRef:
      name: the-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: the-task
spec:
  steps:
  - args:
    - 01 version
    command:
    - echo
    image: registry.access.redhat.com/ubi8/ubi
    name: echo
  - args:
    - -l
    - /
    command:
    - ls
    image: registry.access.redhat.com/ubi8/ubi
    name: lslslash
  - args:
    - -l
    command:
    - ls
    image: registry.access.redhat.com/ubi8/ubi
    name: lsl-ubi
  - command:
    - pwd
    image: registry.access.redhat.com/ubi8/ubi
    name: pwd
  - command:
    - ls
    image: registry.access.redhat.com/ubi8/ubi
    name: ls
  - command:
    - env
    image: registry.access.redhat.com/ubi8/ubi
    name: env
  - args:
    - -c
    - echo stuff > file; ls; cat file
    command:
    - /bin/bash
    image: registry.access.redhat.com/ubi8/ubi
    name: write
  - args:
    - -l
    command:
    - ls
    image: registry.access.redhat.com/ubi8/ubi
    name: lsafterfilemissing

